name: nerfus
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - python=3.10.12
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.45.3
  - tk=8.6.12
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - ansi2html==1.9.1
      - anyio==4.2.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - av==11.0.0
      - awscli==1.32.28
      - babel==2.14.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - bidict==0.22.1
      - bleach==6.1.0
      - blinker==1.7.0
      - boto3==1.34.142
      - botocore==1.34.28
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.28.1
      - colorama==0.4.4
      - colorlog==6.8.0
      - comet-ml==3.37.0
      - comm==0.2.1
      - configargparse==1.7
      - configobj==5.0.8
      - contourpy==1.2.0
      - cryptography==42.0.1
      - cycler==0.12.1
      - dash==2.14.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - diffusers==0.12.1
      - dill==0.3.8
      - dm-tree==0.1.8
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - docutils==0.16
      - dotmap==1.3.30
      - dulwich==0.21.7
      - email-validator==2.2.0
      - embreex==2.17.7.post4
      - everett==3.1.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - fire==0.5.0
      - flask==3.0.1
      - flatbuffers==23.5.26
      - fonttools==4.47.2
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - functorch==1.13.1
      - gast==0.5.4
      - gdown==5.0.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-auth==2.27.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - gputil==1.4.0
      - grpcio==1.60.0
      - gsplat==0.1.6
      - h11==0.14.0
      - h5py==3.10.0
      - httpcore==1.0.2
      - httptools==0.6.1
      - httpx==0.26.0
      - huggingface-hub==0.20.3
      - idna==3.6
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.0.1
      - ipykernel==6.29.0
      - ipython==8.20.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jaxlib==0.4.26
      - jaxtyping==0.2.25
      - jedi==0.19.1
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.2
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - jupyterlab-widgets==3.0.9
      - keras==2.15.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==16.0.6
      - lightning==2.3.3
      - lightning-cloud==0.5.70
      - lightning-sdk==0.1.10
      - lightning-utilities==0.10.1
      - lit==17.0.6
      - litdata==0.2.13
      - lxml==5.1.0
      - mapbox-earcut==1.0.1
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.4
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mediapy==1.2.0
      - mistune==3.0.2
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - msgpack==1.0.7
      - msgpack-numpy==0.4.8
      - multidict==6.0.4
      - multiprocess==0.70.16
      - nbclient==0.9.0
      - nbconvert==7.14.2
      - nbformat==5.9.2
      - nerfacc==0.3.5
      - nerfstudio==0.1.19
      - nerfus==0.0.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nodeenv==1.8.0
      - notebook==7.0.7
      - notebook-shim==0.2.3
      - numpy==1.26.3
      - nuscenes-devkit==1.1.9
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu12==12.3.107
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - open3d==0.18.0
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.9.0.80
      - opt-einsum==3.3.0
      - orjson==3.10.6
      - overrides==7.6.0
      - packaging==23.2
      - pandas==2.2.0
      - pandocfilters==1.5.1
      - parso==0.8.3
      - pathos==0.3.1
      - pexpect==4.9.0
      - pillow==10.2.0
      - pip==24.1.2
      - platformdirs==4.1.0
      - plotly==5.18.0
      - pox==0.3.3
      - ppft==1.7.6.7
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.43
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pycollada==0.8
      - pycparser==2.21
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyequilib==0.5.8
      - pygments==2.17.2
      - pyjwt==2.8.0
      - pyliblzfse==0.4.1
      - pymeshlab==2023.12
      - pyngrok==7.0.5
      - pyparsing==3.1.1
      - pyquaternion==0.9.9
      - pysdf==0.1.9
      - pysocks==1.7.1
      - python-box==6.1.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - python-engineio==4.8.2
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - python-socketio==5.11.0
      - pytorch-lightning==1.8.6
      - pytorch-msssim==1.0.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - rawpy==0.19.0
      - referencing==0.32.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rpds-py==0.17.1
      - rsa==4.7.2
      - rtree==1.2.0
      - s3transfer==0.10.0
      - scikit-image==0.22.0
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - semantic-version==2.10.0
      - send2trash==1.8.2
      - sentry-sdk==1.39.2
      - setproctitle==1.3.3
      - shapely==2.0.2
      - shellingham==1.5.4
      - shtab==1.6.5
      - simple-term-menu==1.6.4
      - simple-websocket==1.0.0
      - simplejson==3.19.2
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - splines==0.3.0
      - stack-data==0.6.3
      - starlette==0.37.2
      - stl==0.0.3
      - svg-path==6.3
      - sympy==1.12
      - tenacity==8.2.3
      - tensorboard==2.9.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - tensorflow-probability==0.23.0
      - termcolor==2.4.0
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tifffile==2023.12.9
      - timm==0.6.7
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==1.13.0
      - torch-fidelity==0.3.0
      - torchaudio==0.13.0
      - torchmetrics==1.3.0.post0
      - torchtyping==0.1.4
      - torchvision==0.14.1
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.1
      - trimesh==4.0.10
      - triton==2.0.0
      - typeguard==2.13.3
      - typer==0.12.3
      - types-python-dateutil==2.8.19.20240106
      - typing-extensions==4.9.0
      - tyro==0.7.0
      - tzdata==2023.4
      - u-msgpack-python==2.8.0
      - ujson==5.10.0
      - uri-template==1.3.0
      - urllib3==2.0.7
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - vhacdx==0.0.5
      - viser==0.1.21
      - wandb==0.16.2
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.3.3
      - websockets==12.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - wrapt==1.14.1
      - wsproto==1.2.0
      - wurlitzer==3.0.3
      - xatlas==0.0.8
      - xxhash==3.4.1
      - yarl==1.9.4
      - yourdfpy==0.0.56
      - zipp==3.17.0
